manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ottojo
      url-base: https://github.com/ottojo

  projects:
    - name: zephyr
      remote: ottojo
      revision: usbc-experiments
      import:
        name-allowlist:
          - cmsis

    - name: otterpill_zephyr
      remote: ottojo
      revision: main

    - name: stm32_comp
      repo-path: zephyr_stm32_comp
      remote: ottojo
      revision: main
      import: true
