manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ottojo
      url-base: https://github.com/ottojo

  projects:
    - name: zephyr
      remote: ottojo
      revision: otterpill
      import:
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)

